# to view
hts_id = ""
# account
cano = "" # first ????????-xx
acnt_prdt_cd = "" # last xxxxxxxx-??
# auth
app_key = ""
app_secret=""
# environment
environment=""
# auth for view(real env)
real_appkey = ""
real_appsecret = ""

# optional fields
# approval_key = ""
# token = ""
# real_approval_key = ""
# real_token = ""
